### PR TITLE
Refactor sample app sdk import

### PR DESCRIPTION
**Pull request by avlaev**
Enable usage of mpin sdk without crypto lib dependency

### CODE REVIEW

**Comment by tatiNo5** [comment]
Can you fix the readme too?

**Comment by tatiNo5** [comment]
Can you make it to depend on a library instead of using a submodule to the sdk?

**Comment by tatiNo5** [comment]
Please, review the samples and use only MPinMFA class.

**Comment by avlaev** [comment]
The Mpin usages have been removed and replaced with the appropraite MpinMFA calls.

**Comment by tatiNo5** [comment]
If you could just squash the last two commits?

**Pull request merged**
