### PR TITLE
Cocoapods samples update

### PR DESCRIPTION
**Pull request by Foriger**
Cocoapods for the sample applications.

### CODE REVIEW

**Comment by tatiNo5** [comment]
can you remove the last merge commit?

**Comment by avlaev** [comment]
The `MobileAppLoginSample` doesn't build at the moment if I select to build it for Devices(not simulators). The error has to do with Xcode not being able to find some symbols from the MfaSdk. I was able to fix it by increasing the Deployment target for both the *project* and the *target* from 8.0 to 12.0 to conform with the minimum requirements we have for the MfaSDK.

**Comment by Foriger** [comment]
> The `MobileAppLoginSample` doesn't build at the moment if I select to build it for Devices(not simulators). The error has to do with Xcode not being able to find some symbols from the MfaSdk. I was able to fix it by increasing the Deployment target for both the _project_ and the _target_ from 8.0 to 12.0 to conform with the minimum requirements we have for the MfaSDK.

Hm, strange. Let me investigate.

**Comment by avlaev** [comment]
The build for the WebsiteLogin sample works but because of a hack we did before. In the project and target build settings for supported and valid architectures we have specified only arm64, but it should now be the default project settings $(ARCHS_STANDARD) which will include simulator architectures as well. This will go with increasing the deployment target to iOS 12 for project and target. Note that this is not a bug with your cocoapods integration but is something which will enable the sample to work with simulators now that the MfaSdk supports all architectures in one binary.

**Comment by tatiNo5** [comment]
Can you update the Setup section of the DVSSample readme with the pods info?

**Comment by tatiNo5** [comment]
I cannot build the DVS sample after `pod install` due to:
`ld: library not found for -lPods-DVSSample`

**Comment by tatiNo5** [comment]
WebsiteLogin sample is build with lots of warnings. Didn't we clean it before?

**Comment by tatiNo5** [comment]
The same for the MobileLoginSample -> lots of warnings

**Pull request merged**
